# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - uis-web-edudatabot-cancentral

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://uis2resgistry.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_0f10233d188b4513b65411fd84ad5b9a }}
        password: ${{ secrets.AzureAppService_ContainerPassword_227effeb0a9e47159d7f9e05339d2dc1 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: uis2resgistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_0f10233d188b4513b65411fd84ad5b9a }}/uis-vis-app:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'uis-web-edudatabot-cancentral'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_948f20ae1a4844f295275f076e580587 }}
        images: 'uis2resgistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_0f10233d188b4513b65411fd84ad5b9a }}/uis-vis-app:${{ github.sha }}'